#!/usr/bin/env python3
"""Generate the hardcoded escaped-null tables for the x64 HUNK_fix_pointers loader.

Runs the MOBD walker (x64nulls.Walk) over the shared .LVL containers, validates
each result, and emits a C header of per-container null-offset tables keyed by the
DATA-hunk size (which HUNK_fix_pointers already receives as `data_size`, and which
is unique per file). Each listed offset is a 4-byte pointer FIELD that currently
holds 0 (an escaped null / array terminator absent from the RLLC) and must be
widened to an 8-byte NULL on x64 so the packed layout stays aligned.

Usage:  python3 gen_x64_nulls.py <LEVELS/640 dir>  > ../src/kknd/mobd_x64_nulls.h
"""
import sys
from lvl import load
from x64nulls import Walk
import sections

# Shared MOBD containers + every per-mission level file. MOBD nulls come from the
# graph walker; CPLC/MAPD/BOXD-grid nulls from sections.py. (BOXD collision-tree
# terminators are a KNOWN gap - not yet enumerated; see kknd-x64-sections memory.)
CONTAINERS = ["WAIT", "SUPSPR", "SPRITES", "SUPER",
              "SURV_01", "SURV_02", "MUTE_01", "MUTE_02", "MLTI_01"]


def main(lvldir):
    out = []
    out.append("// GENERATED by tools/gen_x64_nulls.py - DO NOT EDIT.")
    out.append("// Escaped-null pointer-field offsets (into the DATA hunk body) that are")
    out.append("// absent from the RLLC and must be widened to 8-byte NULL on x64.")
    out.append("// Keyed by DATA-hunk size (unique per shared container). See")
    out.append("// tools/x64nulls.py and memory kknd-mobd-format.")
    out.append("#pragma once")
    out.append("#include <stddef.h>")
    out.append("#include <stdint.h>")
    out.append("")
    entries = []
    errs = False
    for name in CONTAINERS:
        lvl = load(f"{lvldir}/{name}.LVL")
        w = Walk(lvl).run()
        mobd = set(w.extra_slots())
        cplc, mapd, boxd = (sections.cplc_nulls(lvl), sections.mapd_nulls(lvl),
                            sections.boxd_grid_nulls(lvl))
        extra = sorted(mobd | cplc | mapd | boxd)
        # validate the COMBINED set: in-bounds, disjoint from RLLC. (Values need NOT
        # be 0 - pointer-sized scalar fields like CplcSpawnParams.task are widened
        # value-preserving; the loader zero-extends whatever 4-byte value is there.)
        probs = []
        for o in extra:
            if o + 4 > len(lvl.data):
                probs.append(f"{o:#x}: OOB")
            if o in lvl.ptr_slots:
                probs.append(f"{o:#x}: in RLLC")
        sys.stderr.write(
            f"{name}: data_size={len(lvl.data)} extra={len(extra)} "
            f"(MOBD={len(mobd)} CPLC={len(cplc)} MAPD={len(mapd)} BOXDgrid={len(boxd)}) "
            f"{'OK' if not probs else 'PROBLEMS'}\n")
        for p in probs[:10]:
            sys.stderr.write(f"    !! {p}\n")
            errs = True
        arr = f"mobd_x64_nulls_{name.lower()}"
        out.append(f"static const uint32_t {arr}[] = {{")
        for i in range(0, len(extra), 12):
            out.append("  " + " ".join(f"0x{o:06x}," for o in extra[i:i + 12]))
        out.append("};")
        out.append("")
        entries.append((len(lvl.data), arr, len(extra)))

    out.append("typedef struct {")
    out.append("  size_t data_size;        // identifies the container")
    out.append("  const uint32_t *offsets; // extra null slots to widen (value 0)")
    out.append("  size_t count;")
    out.append("} MobdX64NullTable;")
    out.append("")
    out.append("static const MobdX64NullTable g_mobd_x64_null_tables[] = {")
    for size, arr, n in entries:
        out.append(f"  {{ {size}u, {arr}, {n} }},")
    out.append("};")
    out.append("static const size_t g_mobd_x64_null_table_count = "
               f"{len(entries)};")
    out.append("")
    if errs:
        sys.stderr.write("VALIDATION FAILED - not writing usable header\n")
        return 1
    sys.stdout.write("\n".join(out) + "\n")
    return 0


if __name__ == "__main__":
    d = sys.argv[1] if len(sys.argv) > 1 else "/mnt/c/src/bloomberg/c/okk/LEVELS/640"
    sys.exit(main(d))
